# Generated by Django 3.2.19 on 2023-06-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0004_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
