# Generated by Django 3.2.19 on 2023-06-13 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0006_category_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_title',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
