# Generated by Django 3.2.19 on 2023-06-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0007_comment_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_title',
            field=models.CharField(max_length=80),
        ),
    ]
