# Generated by Django 3.2.19 on 2023-06-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0008_alter_comment_comment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_title',
            new_name='title',
        ),
    ]
