# Generated by Django 3.2.19 on 2023-06-25 12:26

import autoslug.fields
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=django.contrib.auth.models.User),
        ),
    ]
