# Generated by Django 3.2.19 on 2023-06-26 01:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0012_alter_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='computer',
            field=models.TextField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
