# Generated by Django 3.2.19 on 2023-06-26 19:36

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0015_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
