# Generated by Django 3.2.19 on 2023-06-26 22:35

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0019_alter_comment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
