# Generated by Django 3.2.19 on 2023-07-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0023_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
