# Generated by Django 3.2.19 on 2023-07-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0025_alter_link_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(),
        ),
    ]
