# Generated by Django 3.2.19 on 2023-07-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0027_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='default-user.png', max_length=60),
        ),
    ]
