# Generated by Django 3.2.19 on 2023-07-24 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retro', '0032_article_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.ManyToManyField(choices=[(0, 'Not rated'), (1, 'Really Low'), (2, 'Low'), (3, 'Medium'), (4, 'Good'), (5, 'Excellent')], default=0, related_name='article_rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
