# Generated by Django 3.2.19 on 2023-07-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0033_alter_article_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rating',
        ),
    ]
