# Generated by Django 3.2.19 on 2023-07-27 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0035_article_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='rating',
            new_name='ratings',
        ),
    ]
