# Generated by Django 3.2.19 on 2023-08-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0036_rename_rating_article_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
