# Generated by Django 3.2.19 on 2023-08-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0037_remove_comment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
