# Generated by Django 3.2.19 on 2023-08-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0043_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
