# Generated by Django 3.2.19 on 2023-08-21 20:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0049_auto_20230821_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
