# Generated by Django 3.2.19 on 2023-08-21 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0053_comment_comment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_title',
        ),
    ]
