# Generated by Django 3.2.19 on 2023-08-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0057_remove_article_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='ratings',
        ),
    ]
